"""initial

Revision ID: e3aaec7424dc
Revises:
Create Date: 2026-06-17 02:58:28.402364+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e3aaec7424dc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "USER_CREATED",
                "USER_DEACTIVATED",
                "CLIENT_ANONYMIZED",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column("performed_by_id", sa.Integer(), nullable=True),
        sa.Column("performed_by_name", sa.String(length=255), nullable=True),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("target_user_name", sa.String(length=255), nullable=True),
        sa.Column("target_user_email", sa.String(length=255), nullable=True),
        sa.Column("target_user_role", sa.String(length=50), nullable=True),
        sa.Column("target_client_id", sa.Integer(), nullable=True),
        sa.Column("target_client_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("cpf", sa.String(length=11), nullable=True),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_clients_created_by", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name="fk_clients_updated_by", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cnpj", name="uq_clients_cnpj"),
        sa.UniqueConstraint("cpf", name="uq_clients_cpf"),
    )
    op.create_index(op.f("ix_clients_cnpj"), "clients", ["cnpj"], unique=False)
    op.create_index(op.f("ix_clients_cpf"), "clients", ["cpf"], unique=False)
    op.create_index(
        op.f("ix_clients_deleted_at"), "clients", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_table(
        "forensic_holidays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "NATIONAL",
                "COURT",
                "COMARCA",
                name="holidayscope",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("court", sa.String(length=50), nullable=True),
        sa.Column("comarca", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "date", "scope", "court", "comarca", name="uq_forensic_holidays_natural"
        ),
    )
    op.create_index(
        "ix_forensic_holidays_date", "forensic_holidays", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_forensic_holidays_id"), "forensic_holidays", ["id"], unique=False
    )
    op.create_index(
        "ix_forensic_holidays_scope_court_comarca",
        "forensic_holidays",
        ["scope", "court", "comarca"],
        unique=False,
    )
    op.create_table(
        "office_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("office_name", sa.String(length=255), nullable=True),
        sa.Column("cnpj", sa.String(length=18), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("instagram_url", sa.String(length=500), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("whatsapp_url", sa.String(length=500), nullable=True),
        sa.Column("hero_title", sa.String(length=255), nullable=True),
        sa.Column("hero_subtitle", sa.String(length=1000), nullable=True),
        sa.Column("hero_image_url", sa.String(length=500), nullable=True),
        sa.Column("about_title", sa.String(length=255), nullable=True),
        sa.Column("about_description", sa.Text(), nullable=True),
        sa.Column("about_image_url", sa.String(length=5000), nullable=True),
        sa.Column("lawyer_name", sa.String(length=255), nullable=True),
        sa.Column("lawyer_oab", sa.String(length=50), nullable=True),
        sa.Column("lawyer_description", sa.Text(), nullable=True),
        sa.Column("lawyer_image_url", sa.String(length=5000), nullable=True),
        sa.Column("differentials", sa.JSON(), nullable=True),
        sa.Column("areas_of_practice", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_office_config_id"), "office_config", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reset_token_hash", sa.String(length=64), nullable=True),
        sa.Column("reset_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_users_created_by", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name="fk_users_updated_by", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", name="articlestatus"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
    op.create_table(
        "client_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_client_notes_created_by",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name="fk_client_notes_updated_by",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_notes_client_id"), "client_notes", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_notes_deleted_at"), "client_notes", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_client_notes_id"), "client_notes", ["id"], unique=False)
    op.create_table(
        "google_credential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=False),
        sa.Column("scope", sa.String(length=500), nullable=True),
        sa.Column(
            "connected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_google_credential_user"),
    )
    op.create_index(
        op.f("ix_google_credential_id"), "google_credential", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_google_credential_user_id"),
        "google_credential",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NOVO",
                "EM_ATENDIMENTO",
                "FECHADO",
                "DESCARTADO",
                name="leadstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_email"), "leads", ["email"], unique=False)
    op.create_index(op.f("ix_leads_id"), "leads", ["id"], unique=False)
    op.create_table(
        "notification_preference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "PROCESS_MOVEMENT_CREATED",
                "PROCESS_STATUS_CHANGED",
                "LEAD_ASSIGNED",
                "TASK_ASSIGNED",
                "DEADLINE_APPROACHING",
                "DEADLINE_EXPIRED",
                "EXTERNAL_API_FAILURE",
                name="notification_event_type",
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "event_type", name="uq_notification_pref_user_event"
        ),
    )
    op.create_index(
        "ix_notification_pref_user_id",
        "notification_preference",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preference_id"),
        "notification_preference",
        ["id"],
        unique=False,
    )
    op.create_table(
        "processes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("court", sa.String(length=120), nullable=False),
        sa.Column("tribunal_alias", sa.String(length=30), nullable=True),
        sa.Column("action_type", sa.String(length=120), nullable=False),
        sa.Column("opposing_party", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ATIVO",
                "SUSPENSO",
                "ARQUIVADO",
                "ENCERRADO",
                name="processstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_processes_created_by", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name="fk_processes_updated_by", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number", name="uq_processes_number"),
    )
    op.create_index(
        op.f("ix_processes_client_id"), "processes", ["client_id"], unique=False
    )
    op.create_index(op.f("ix_processes_id"), "processes", ["id"], unique=False)
    op.create_index(op.f("ix_processes_number"), "processes", ["number"], unique=False)
    op.create_index(
        op.f("ix_processes_tribunal_alias"),
        "processes",
        ["tribunal_alias"],
        unique=False,
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "AUDIENCIA",
                "REUNIAO",
                "PRAZO",
                "OUTRO",
                name="appointmenttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("google_event_id", sa.String(length=1024), nullable=True),
        sa.Column("is_synced_to_google", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_appointments_created_by",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_appointments_client_id", "appointments", ["client_id"], unique=False
    )
    op.create_index(
        "ix_appointments_created_by", "appointments", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_appointments_id"), "appointments", ["id"], unique=False)
    op.create_index(
        "ix_appointments_process_id", "appointments", ["process_id"], unique=False
    )
    op.create_index(
        "ix_appointments_starts_at", "appointments", ["starts_at"], unique=False
    )
    op.create_table(
        "deadlines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("business_days", sa.Integer(), nullable=False),
        sa.Column("deadline_type", sa.String(length=120), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("court", sa.String(length=120), nullable=True),
        sa.Column("comarca", sa.String(length=120), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_deadlines_created_by", use_alter=True
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deadlines_id"), "deadlines", ["id"], unique=False)
    op.create_index(
        "ix_deadlines_process_due",
        "deadlines",
        ["process_id", "due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadlines_process_id"), "deadlines", ["process_id"], unique=False
    )
    op.create_table(
        "external_api_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "DATAJUD", name="externalapiprovider", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "operation",
            sa.Enum(
                "PROCESS_MOVEMENT_SYNC",
                name="externalapioperation",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCESS",
                "FAILURE",
                name="externalapistatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("tribunal_alias", sa.String(length=30), nullable=True),
        sa.Column("request_identifier", sa.String(length=120), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_external_api_logs_created_by",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_api_logs_id"), "external_api_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_external_api_logs_operation"),
        "external_api_logs",
        ["operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_api_logs_process_id"),
        "external_api_logs",
        ["process_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_api_logs_provider"),
        "external_api_logs",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_api_logs_status"),
        "external_api_logs",
        ["status"],
        unique=False,
    )
    op.create_table(
        "process_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL", "SYSTEM", name="movementsource", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_process_movements_created_by",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "process_id", "external_id", name="uq_process_movements_process_external_id"
        ),
    )
    op.create_index(
        op.f("ix_process_movements_external_id"),
        "process_movements",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_movements_id"), "process_movements", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_process_movements_process_id"),
        "process_movements",
        ["process_id"],
        unique=False,
    )
    op.create_index(
        "ix_process_movements_process_occurred",
        "process_movements",
        ["process_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "process_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_process_notes_created_by",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name="fk_process_notes_updated_by",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_process_notes_id"), "process_notes", ["id"], unique=False)
    op.create_index(
        op.f("ix_process_notes_process_id"),
        "process_notes",
        ["process_id"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                name="taskpriority",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "TODO",
                "IN_PROGRESS",
                "BLOCKED",
                "DONE",
                name="taskstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("assigned_to", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"], ["users.id"], name="fk_tasks_assigned_to", use_alter=True
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_tasks_created_by", use_alter=True
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name="fk_tasks_updated_by", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tasks_assigned_to", "tasks", ["assigned_to"], unique=False)
    op.create_index("ix_tasks_client_id", "tasks", ["client_id"], unique=False)
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index("ix_tasks_process_id", "tasks", ["process_id"], unique=False)
    op.create_index("ix_tasks_status_order", "tasks", ["status", "order"], unique=False)
    op.create_table(
        "deadline_alert",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deadline_id", sa.Integer(), nullable=False),
        sa.Column("days_before", sa.Integer(), nullable=False),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["deadline_id"], ["deadlines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "deadline_id", "days_before", name="uq_deadline_alert_deadline_days"
        ),
    )
    op.create_index(
        op.f("ix_deadline_alert_deadline_id"),
        "deadline_alert",
        ["deadline_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadline_alert_id"), "deadline_alert", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deadline_alert_id"), table_name="deadline_alert")

    op.drop_index(op.f("ix_deadline_alert_deadline_id"), table_name="deadline_alert")
    op.drop_table("deadline_alert")
    op.drop_index("ix_tasks_status_order", table_name="tasks")
    op.drop_index("ix_tasks_process_id", table_name="tasks")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_index("ix_tasks_client_id", table_name="tasks")
    op.drop_index("ix_tasks_assigned_to", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_process_notes_process_id"), table_name="process_notes")
    op.drop_index(op.f("ix_process_notes_id"), table_name="process_notes")
    op.drop_table("process_notes")
    op.drop_index(
        "ix_process_movements_process_occurred", table_name="process_movements"
    )
    op.drop_index(
        op.f("ix_process_movements_process_id"), table_name="process_movements"
    )
    op.drop_index(op.f("ix_process_movements_id"), table_name="process_movements")
    op.drop_index(
        op.f("ix_process_movements_external_id"), table_name="process_movements"
    )
    op.drop_table("process_movements")
    op.drop_index(op.f("ix_external_api_logs_status"), table_name="external_api_logs")
    op.drop_index(op.f("ix_external_api_logs_provider"), table_name="external_api_logs")
    op.drop_index(
        op.f("ix_external_api_logs_process_id"), table_name="external_api_logs"
    )
    op.drop_index(
        op.f("ix_external_api_logs_operation"), table_name="external_api_logs"
    )
    op.drop_index(op.f("ix_external_api_logs_id"), table_name="external_api_logs")
    op.drop_table("external_api_logs")
    op.drop_index(op.f("ix_deadlines_process_id"), table_name="deadlines")
    op.drop_index("ix_deadlines_process_due", table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_id"), table_name="deadlines")
    op.drop_table("deadlines")
    op.drop_index("ix_appointments_starts_at", table_name="appointments")
    op.drop_index("ix_appointments_process_id", table_name="appointments")
    op.drop_index(op.f("ix_appointments_id"), table_name="appointments")
    op.drop_index("ix_appointments_created_by", table_name="appointments")
    op.drop_index("ix_appointments_client_id", table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_processes_tribunal_alias"), table_name="processes")
    op.drop_index(op.f("ix_processes_number"), table_name="processes")
    op.drop_index(op.f("ix_processes_id"), table_name="processes")
    op.drop_index(op.f("ix_processes_client_id"), table_name="processes")
    op.drop_table("processes")
    op.drop_index(
        op.f("ix_notification_preference_id"), table_name="notification_preference"
    )
    op.drop_index("ix_notification_pref_user_id", table_name="notification_preference")
    op.drop_table("notification_preference")
    op.drop_index(op.f("ix_leads_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_email"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_google_credential_user_id"), table_name="google_credential")
    op.drop_index(op.f("ix_google_credential_id"), table_name="google_credential")
    op.drop_table("google_credential")
    op.drop_index(op.f("ix_client_notes_id"), table_name="client_notes")
    op.drop_index(op.f("ix_client_notes_deleted_at"), table_name="client_notes")
    op.drop_index(op.f("ix_client_notes_client_id"), table_name="client_notes")
    op.drop_table("client_notes")
    op.drop_index(op.f("ix_articles_id"), table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_office_config_id"), table_name="office_config")
    op.drop_table("office_config")
    op.drop_index(
        "ix_forensic_holidays_scope_court_comarca", table_name="forensic_holidays"
    )
    op.drop_index(op.f("ix_forensic_holidays_id"), table_name="forensic_holidays")
    op.drop_index("ix_forensic_holidays_date", table_name="forensic_holidays")
    op.drop_table("forensic_holidays")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_deleted_at"), table_name="clients")
    op.drop_index(op.f("ix_clients_cpf"), table_name="clients")
    op.drop_index(op.f("ix_clients_cnpj"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # Native Postgres enum types must be dropped explicitly after their tables
    op.execute("DROP TYPE IF EXISTS auditaction")
    op.execute("DROP TYPE IF EXISTS role")
    op.execute("DROP TYPE IF EXISTS articlestatus")
    op.execute("DROP TYPE IF EXISTS notification_event_type")
    # ### end Alembic commands ###
